Instagram/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Instagram.Models
{
    public class Comment
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        
        public DateTime CommentDate { get; set; }
        
        public int UserId { get; set; }
        public User User { get; set; }
        public int PostId { get; set; }
        public Post Post { get; set; }
    }
}

Instagram/ViewModels/CommentsViewModel.cs
using System.Collections.Generic;
using Instagram.Models;

namespace Instagram.ViewModels
{
    public class CommentsViewModel
    {
        public User User { get; set; }
        public  int UserId { get; set; }
        public Post Post { get; set; }
        public int PostId { get; set; }
        public List<Comment> Comments { get; set; }
    }
}

Instagram/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Instagram.Models;
using Instagram.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace Instagram.Controllers
{
    public class HomeController : Controller
    {
        private InstagramContext context;

        
        
        public HomeController(InstagramContext context)
        {
            this.context = context;
            
        }
        
        [Authorize]
        public IActionResult Index()
        {
            

            User user = context.Users.Include(u => u.Posts).ThenInclude(c => c.Comments).FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            IQueryable<Subscription> userSubscriptions = context.Subscriptions.Where(s => s.SubscriberId == user.Id);
//            List<Post> posts = context.Posts.Include(c => c.Comments).ToList();
            List<Post> posts = new List<Post>();
            foreach (Subscription s in userSubscriptions)
            {
                User follower = context.Users.Include(p => p.Posts).ThenInclude(c => c.Comments).FirstOrDefault(u => u.Id == s.ToSubscribeId);
                posts.AddRange(follower.Posts);
            }
            posts.AddRange(user.Posts);

            IndexModel model = new IndexModel()
            {
                User = user,
                PostsFeed = posts.OrderByDescending(p => p.PostDate).ToList(),
            };

            return View(model);
        }

        public IActionResult Profile(int userId)
        {
            User user = context.Users.Include(u => u.Posts).FirstOrDefault(u => u.Id == userId );
            User viewUser = context.Users.FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            ProfileModel model = new ProfileModel()
            {
                User = user,
                ViewerUser = viewUser,
                isSubscribed = context.Subscriptions.FirstOrDefault(
                    s => s.SubscriberId == viewUser.Id && s.ToSubscribeId == user.Id) != null
            };

            return View(model);
        }

//        public IActionResult Search(string key)
//        {
//            List<User> users = context.Users.ToList();
//            if (!string.IsNullOrEmpty(key))
//            {
//                users = users.Where(u => 
//                    u.Login.Contains(key) || u.Name.Contains(key) || u.Email.Contains(key)).ToList();
//            }
//
//            return View(users);
//        }
        public IActionResult SearchAjax()
        {
            return View();
        }

        public IActionResult SearchAjaxResult(string keyWord)
        {
            List<User> users = context.Users.ToList();
                
            if (!string.IsNullOrEmpty(keyWord))
            {
               users = context.Users.Where(u =>
                    u.Name.Contains(keyWord) ||
                    u.Email.Contains(keyWord)).ToList();
            }

            return PartialView("UserSearchResult", users);
        }
        
        


    }
}

Instagram/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Instagram.Models;
using Instagram.Services;
using Instagram.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Instagram.Controllers
{
    public class PostController : Controller
    {
        private InstagramContext context;
        private FileUploadService fileUploadService;
        private IHostingEnvironment environment;

        public PostController(InstagramContext context, 
            FileUploadService fileUploadService,
            IHostingEnvironment environment)
        {
            this.context = context;
            this.fileUploadService = fileUploadService;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(CreatePostModel model)
        {
            User user = context.Users.FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = new Post()
            {
                Title = model.Title,
                UserId = user.Id,
                PostDate = DateTime.Now,
                PostImagePath = $"images/{user.Login}/{model.PostImage.FileName}"
            };

            context.Posts.Add(post);

            string path = Path.Combine(
                environment.WebRootPath,
                $"images/{user.Login}_{model.PostImage.FileName}");

            fileUploadService.Upload(path, model.PostImage.FileName, model.PostImage);
            user.PostCounter++;
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        
        
        [HttpPost]
        public IActionResult Like(int postId)
        {
            User user = context.Users.Include(u => u.Posts).FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = context.Posts.FirstOrDefault(p => p.Id == postId);

            context.Likes.Add(new Like()
            {
                LikeDate = DateTime.Now,
                PostId = postId,
                User = user
            });
            
            post.Likes++;
            context.SaveChanges();
            return Json(post.Likes);

//            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        public IActionResult DisLike(int postId)
        {
            User user = context.Users.Include(u => u.Posts).FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = context.Posts.FirstOrDefault(p => p.Id == postId);
            if (post.Likes != null)
            {
                Like like = context.Likes.FirstOrDefault(l => l.PostId == post.Id && l.UserId == user.Id);
                context.Likes.Remove(like);
                
                post.Likes --;
            }
            context.SaveChanges();
            
            return Json(post.Likes);
//            return RedirectToAction("Index", "Home");
        }
        
        
        
        public IActionResult Details(int id)
        {
            User user = context.Users.Include(u => u.Posts)
                .FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = context.Posts.FirstOrDefault(p => p.Id == id);
            List<Comment> comments = new List<Comment>();
            PostDetailsViewModel model = new PostDetailsViewModel()
            {
                User = user,
                Post = post,
                
                CommentsViewModel = new CommentsViewModel()
                {
                    UserId = user.Id,
                    PostId = post.Id,
                    Comments = comments.OrderByDescending(p => p.CommentDate).ToList()
                }
           
            return View(model);
        }
        
        
        [HttpPost]
        public IActionResult Comment(int postId, string userId, string text)
        {
            User user = context.Users.Include(u => u.Posts).FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = context.Posts.FirstOrDefault(p => p.Id == postId);
            Comment comment = new Comment() {Text = text, CommentDate = DateTime.Now, UserId = user.Id, PostId = post.Id};
            context.Comments.Add(comment);
            
            context.SaveChanges();

            return Json(comment.Text);
//            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        public IActionResult Edit(int postId)
        {
            User user = context.Users.Include(u => u.Posts)
                .FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            Post post = context.Posts.FirstOrDefault(p => p.Id == postId);
            context.Posts.Update(post);
            context.SaveChanges();
            return Json(post.Title);
//            return RedirectToAction("Index", "Home", new {post.Id});
        }
    }
}

Instagram/Controllers/SubscriptionController.cs
using System.IO;
using System.Linq;
using Instagram.Models;
using Instagram.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Instagram.Controllers
{
    public class SubscriptionController : Controller
    {
        private InstagramContext context;


        public SubscriptionController(InstagramContext context)
        {
            this.context = context;
        }

        
        public string Subscribe(string currentUserLogin, int followersId)
        {
            User user = context.Users.FirstOrDefault(u => u.Login == currentUserLogin);
            User followers = context.Users.FirstOrDefault(u => u.Id == followersId);
            Subscription subscription = new Subscription()
            {
                SubscriberId = user.Id,
                ToSubscribeId = followersId
            };
            context.Subscriptions.Add(subscription);
            user.Subscriptions++;
            followers.Subscribers++;

            int subscriptions = followers.Subscriptions;
            int subscribers = followers.Subscribers;
            
            context.SaveChanges();
            
            string json2 = "{\"subscriptions\":" + $"{subscriptions}," +  "\"subscribers\":" + $"{subscribers}" + "}";

            string result = "'{" + $"'subscriptions': {subscriptions}, 'subscribers': {subscribers}" + "}'";
            
            var json = JsonConvert.SerializeObject(result);
            return json2;
//            return RedirectToAction("Profile", "Home", new {userId =followers.Id});
        }
        [HttpPost]
        public string UnSubscribe(string currentUserLogin, int followersId)
        {
           
            
            User user = context.Users.FirstOrDefault(u => u.Login == currentUserLogin);
            User followers = context.Users.FirstOrDefault(u => u.Id == followersId);
            Subscription subscription = context.Subscriptions.FirstOrDefault(
                s => s.SubscriberId == user.Id && s.ToSubscribeId == followers.Id
                     );
//            subscription =
//                context.Subscriptions.FirstOrDefault(c => c.SubscriberId == user.Id && c.ToSubscribeId == followers.Id);
            if (subscription != null)
            {
                context.Subscriptions.Remove(subscription);
                user.Subscriptions--;
                followers.Subscribers--;
                context.SaveChanges();
            }
            
//            ProfileModel model = new ProfileModel()
//            {
//                User = user
//            };
            
            int subscriptions = followers.Subscriptions;
            int subscribers = followers.Subscribers;
            string json2 = "{\"subscriptions\":" + $"{subscriptions}," +  "\"subscribers\":" + $"{subscribers}" + "}";
            var json = JsonConvert.SerializeObject("{" + $"'subscriptions': {subscriptions}, 'subscribers': {subscribers}" + "}");
//            return PartialView("../Home/UsersList", model);
//            return Json(new { Url = Url.Action("../Home/UsersList", model) });
//            return Json(new { error = true, message = RenderViewToString(PartialView("Evil", model))});
            return json2;
//            return RedirectToAction("Profile", "Home", new {userId =followers.Id});
        }
        
        
     
    }
}

Instagram/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Instagram/Views/Home/Comments.cshtml
@model Instagram.ViewModels.CommentsViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
        
        
@if(!Model.Comments.Any())
{
    <text>nobody commented yet</text>
}
else
{
    <dl class="dl-horizontal">
        @foreach (Comment comment in Model.Comments)
        {
            <dt>
                @comment.CommentDate.ToString("MM/dd/yyyy")
            </dt>
            <dd>
                @comment.Text
            </dd>
        }
    </dl>

}

@* @{ Html.RenderPartialAsync("PostsList", Model.Comments);} *@

Instagram/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Instagram/Views/Home/Index.cshtml
@model Instagram.ViewModels.IndexModel


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Index</h2>

<div>
    <h2>@Model.User.Login</h2>
    <hr/>
    <img src="~/@Model.User.AvatarImage" width="100" height="100" />
    @Html.ActionLink("Create post", "Create", "Post")
</div>

<div>
    <table>
        <tr>
            <td>Posts</td>
            <td>Followers</td>
            <td>Follow</td>
        </tr>
        <tr>
            <td>@Model.User.PostCounter</td>
            <td>@Model.User.Subscribers</td>
            <td>@Model.User.Subscriptions</td>
        </tr>
    </table>
</div>



@{ Html.RenderPartialAsync("PostsList", Model.PostsFeed);}

Instagram/Views/Home/PostsList.cshtml
@model List<Post>
<div>
    @foreach (Post post in Model)
    {
        <h4>@post.User.Login</h4>
        <img src="~/@post.PostImagePath" width="500" height="500"/>
        <div>
            <input type="button" id="deleteId" onclick="deletePost('@post.Id', '@post.UserId')" value="Delete post"/>
            Likes (<span id="likecount-@post.Id">@post.Likes</span>)<br/>
            <input type="button" id="postLike" onclick="LikePost('@post.Id', '@post.UserId')" value="Like"/>
            <input type="button" id="postDisLike" onclick="DisLikePost('@post.Id', '@post.UserId')" value="DisLike"/>
        </div>
        <div id="editTitleId-@post.Id">
            Title:@post.Title<br/>
            <a onclick="openEditForm(@post.Id)" style="cursor: pointer">Edit title</a>
        </div>
        <div id="editdiv-@post.Id" style="display: none">
            <textarea id="posttext-@post.Id"></textarea>
            <input type="button" id="editId" onclick="editTitle('@post.Id', '@post.User.Login')" value="Edit"/>
        </div>
       
        <div>
            Комментарии (@post.Comments.Count)<br/>
            <a onclick="openCommentForm(@post.Id)" style="cursor: pointer">Оставить комментарий</a>
        </div>
        <div id="postdiv-@post.Id" style="display:none">
            <textarea id="posttext-@post.Id"></textarea>
            <input type="button" id="postComment" onclick="sendComment('@post.Id', '@post.User.Login')" value="Отправить"/>
        </div>
        <div id="commentId-@post.Id">
            @foreach (Comment comment in post.Comments)
            {
                <h5>@comment.UserId</h5>
                <h5>@comment.CommentDate</h5>
                <h5>@comment.Text</h5>
            }
        </div>
        <hr/>         
    }
</div>

<script>

    function openCommentForm(postId) {            
    $('#postdiv-' + postId).show();
    }
    
    function sendComment(postId, userId) {
    $.ajax({
    url: '@Url.Action("Comment", "Post")',
                type: 'POST',
                data: { 'postId': postId, 'userId': userId, 'text': $('#posttext-' + postId).val() },
                success: function(data) {
                    console.log('все ок');
                    console.log(data);
                    $('#commentId-' + postId).html(data);
                },
                error: function() {
                    console.log('Ошибка во время отправки комментария');
                }
            });
        }
    
    function openEditForm(postId) {            
        $('#editdiv-' + postId).show();
    }
    
    function editTitle(postId, userId) {
        $.ajax({
            url: '@Url.Action("Edit", "Post")',
            type: 'POST',
            data: { 'postId': postId, 'userId': userId, 'text': $('#posttext-' + postId).val() },
            success: function(data) {
                console.log('все ок');
                console.log(data);
                $('#editTitleId-' + postId).html(data);
            },
            error: function() {
                console.log('Ошибка во время отправки');
            }
        });
    }
    
    function LikePost(postId, userId) {
        $.ajax({
            url: '@Url.Action("Like", "Post")',
            type: 'Post',
            data: { 'postId': postId, 'userId': userId },
            success: function(data) {
                console.log('все ок');
                console.log(data);
                $('#likecount-' + postId).html(data);
            },
            error: function() {
                console.log('Error Like');
            }
        });
    }
    function DisLikePost(postId, userId) {
        $.ajax({
            url: '@Url.Action("DisLike", "Post")',
            type: 'Post',
            data: { 'postId': postId, 'userId': userId },
            success: function(data) {
                console.log('все ок');
                console.log(data);
                $('#likecount-' + postId).html(data);
            },
            error: function() {
                console.log('Error DisLike');
            }
        });
    }
</script>

Instagram/Views/Home/Profile.cshtml
@using Microsoft.EntityFrameworkCore.Scaffolding.Internal
@model Instagram.ViewModels.ProfileModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profile</h2>

<div>
    <h2>@Model.User.Login</h2>
    <hr/>
    <img src="~/@Model.User.AvatarImage" width="100" height="100" />
</div>

<div id="userAvatar">
    @{ Html.RenderPartialAsync("UsersList", Model);}
    
</div>


@{ Html.RenderPartialAsync("PostsList", Model.User.Posts);}

@section Scripts {
    <script>
        $(document).ready(function() {
            $('#FollowId').click(function(e) {

                e.preventDefault();

                $.ajax({
                    url: '@Url.Action("Subscribe", "Subscription")',
                    type: 'Post',
                    data: { 'currentUserLogin': "@Model.ViewerUser.Login", 'followersId': "@Model.User.Id" },
                    success: function(data) {

                        console.log('все ок');
                        console.log(data);
                        var obj = JSON.parse(data)
                        $('#subscribeForm').hide();
                        $('#unSubscribeForm').show();
                        console.log(obj.subscribers);
                        $('#subscribersId').html(obj.subscribers);
                        $('#subscriptionId').html(obj.subscriptions);
                    },
                    error: function() {
                        console.log('Error');
                    }
                });
            });
        });


        $(document).ready(function() {
            $('#UnfollowId').click(function(e) {

                e.preventDefault();
                $.ajax({
                    url: '@Url.Action("UnSubscribe", "Subscription")',
                    type: 'Post',
                    data: { 'currentUserLogin': "@Model.ViewerUser.Login", 'followersId': "@Model.User.Id" },
                    success: function(data) {
                        console.log('все ок');
                        console.log(data);
                        var obj = JSON.parse(data);
                        console.log(obj.subscribers);
                        $('#subscribeForm').show();
                        $('#unSubscribeForm').hide();
                        $('#subscribersId').html(obj.subscribers);
                        $('#subscriptionId').html(obj.subscriptions);
                    },
                    error: function() {
                        console.log('Error');
                    }
                });
            });
        });

    </script>
}

Instagram/Views/Home/SearchAjax.cshtml
@model IEnumerable<Instagram.Models.User>

@* @{ *@
@*     ViewData["Title"] = "Search"; *@
@* } *@
@* *@
@* <h2>Search</h2> *@
@* *@
@* <form method="get" asp-action="SearchAjax"> *@
@*     <input type="text" name="key" /> *@
@*     <input type="submit" value="Search" /> *@
@* </form> *@
@* <table class="table"> *@
@*     <thead> *@
@*     <tr> *@
@*         <th> *@
@*             @Html.DisplayNameFor(model => model.AvatarImage) *@
@*         </th> *@
@*         <th> *@
@*             @Html.DisplayNameFor(model => model.Login) *@
@*         </th> *@
@*         <th> *@
@*             @Html.DisplayNameFor(model => model.Name) *@
@*         </th> *@
@*     </tr> *@
@*     </thead> *@
@*     <tbody> *@
@*     @foreach (var item in Model) { *@
@*         <tr> *@
@*             <td> *@
@*                 <img src="~/@item.AvatarImage" width="100" height="100"/> *@
@*             </td> *@
@*             <td> *@
@*                 @Html.DisplayFor(modelItem => item.Login) *@
@*             </td> *@
@*             <td> *@
@*                 @Html.DisplayFor(modelItem => item.Name) *@
@*             </td> *@
@*             <td> *@
@*                 @Html.ActionLink("Profile", "Profile", new { userId =item.Id }) | *@
@*             </td> *@
@*         </tr> *@
@*     } *@
@*     </tbody> *@
@* </table> *@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Поиск пользователей</title>
</head>
<body>
<input type="text" name="searchKey" id="search" />
<input type='button' id="submit" value='Найти' />
<div id="results"></div>

@section Scripts
{
    <script>
        $(document).ready(function() {
            $('#submit').click(function(e) {
                e.preventDefault();
                var searchKey = $('#search').val();
                searchKey = encodeURIComponent(searchKey);
                $('#results').load('@Url.Action("SearchAjaxResult", "Home")?keyWord=' + searchKey);
            });
        });
    </script>
}
</body>
</html>

Instagram/Views/Home/UsersList.cshtml
@model Instagram.ViewModels.ProfileModel

@{
    string subscribeFormStyle;
    string unsubscribeFormStyle;
}

@if (!Model.isSubscribed)
{
    subscribeFormStyle = "";
    unsubscribeFormStyle = "display: none;";
}
else
{
    subscribeFormStyle = "display: none;";
    unsubscribeFormStyle = "";
}

<div id="subscribeForm" style="@subscribeFormStyle">
    <form id="subscribeId-@Model.User.Id" method="post" asp-controller="Subscription" asp-action="Subscribe">
        <input type="hidden" name="currentUserLogin" value="@Model.ViewerUser.Login"/>
        <input type="hidden" name="followersId" value="@Model.User.Id"/>
        <input type="button" id="FollowId" value="follow"/>
    </form>
</div>

<div id="unSubscribeForm" style="@unsubscribeFormStyle">
    <form id="unsubscribeId-@Model.User.Id" method="post" asp-controller="Subscription" asp-action="UnSubscribe">
        <input type="hidden" name="currentUserLogin" value="@Model.ViewerUser.Login"/>
        <input type="hidden" name="followersId" value="@Model.User.Id"/>
        <input type="button" id="UnfollowId" value="unfollow"/>
    </form>
</div>

<div>
    <table>
        <tr>
            <td>Posts</td>
            <td>Followers</td>
            <td>Follow</td>
        </tr>
        <tr>
            <td>@Model.User.PostCounter</td>
            <td id="subscribersId">@Model.User.Subscribers</td>
            <td id="subscriptionsId">@Model.User.Subscriptions</td>
        </tr>
    </table>
</div>